### ISSUE TITLE
Data ToDos

### ISSUE THREAD

**Issue by Bathtor** [Bathtor/EPCompendium#1]
If you start a category, reply as a comment.

# Requirements
- [SBT](https://www.scala-sbt.org/)
- Build [API-Facade](https://github.com/Bathtor/api-facade) from source (`sbt publishLocal`)

# Procedure
0. Fork
1. Start a new file (Scala object) with the name of the category in the data project
2. Add `val list: List[<Type>] = Macros.memberList[<Type>];` for the appropriate item type at the end of the object definition.
3. Add all the items to the object definition.
4. Add the `list` field of your new object to the appropriate collection in `AllData`
5. Add your name to the authors list in `AllData`, if you like
6. Check that it compiles and runs with `data/run --script` in sbt
7. Do a PR

# Items
List of what still needs to be entered from the rulebooks.

## Weapons
From *Eclipse Phase* core.

- [x] Blades
- [x] Clubs 1234342d811e6f7a552eef55e3338ebc856b1693
- [x] Unarmed 1512f49d973ffee0083ea94bad5f787b8ae95205
- [x] Kinetic Firearms e5e383ec90783c17522efb1a38b2bece674bc173
- [x] Railguns 45b5492a1eeea21b744e15604db194d1d1c3ea33
- [x] Beam Weapons 08f4f7d9b2e32209b6681056befa792426f5fb87
- [x] Seekers e24eb3239943e26a03e0c8cea584dccfa85ff479
- [x] Spray Weapons 8642217634503ffe3489d8c59879cd10f6dfbef2
- [x] Exotic Stuff 8642217634503ffe3489d8c59879cd10f6dfbef2
- [x] Grenades e56a4bd15c082c44263a8e6b74a102bdf9460392

## Morphs
From *Morph Recognition Guide*

Let's create a few different files here, to avoid having huge mega files.
Since the morph types are a bit too coarse as categories, and MRG is anyway sorted alphabetically, let's just go by that.

- [x] A-C 810e8bc42cba5d9080665b3f4fedd9a1fc90f381
- [x] D-F 61ee3fdcd1cda4fe9452a8326f30580304e0d060
- [x] G-L bc6e150b5b6b021f90bfaabdb66be2fdde83d46d
- [x] M-N 3be54ecb047d60ee78cda28d0eb4afb677768047
- [x] O-R fcb5b27113b502465a24a32f21261279d3f2383e
- [x] S 1db9211cbd5adad70dedc27a6805cbcf286f8480
- [x] T-X df308bf088c6fb52e3117368c84a3326641cf29f

## Traits

- [x] Positive traits from Eclipse Phase core 93333982b1df03539b537baeb8a70d816ed1a460
- [x] Negative traits from Eclipse Phase core 2988a3abb96bb79cd0cfa2f3353657a8eebbe053
- [x] Positive traits from Transhuman 2390781e8986407a38616ad5a1dd9e313cb67f43
- [x] Negative traits from Transhuman 2b6bbf27831854047e1fe84a8bf143a3d05f3a0e
- [x] Neutral traits from Transhuman 58f63fec7ae27c6139913b27de4bf295ae8826e8
- [x] Traits from Firewall 1bc9bd4ead912c0f733dd629c315ac1947b76021
- [x] Traits from Gatecrashing 1bc9bd4ead912c0f733dd629c315ac1947b76021
- [x] Traits from Panopticon 1bc9bd4ead912c0f733dd629c315ac1947b76021
- [x] Traits from Sunward 42b91b5cb727bd30151a6e91b54fd572bbe65f01
- [x] Traits from Rimward 42b91b5cb727bd30151a6e91b54fd572bbe65f01

## Derangements
- [x] Eclipse Phase core deae4c13d989d6674a43b63d275c733b43a8df9c

## Disorders
- [x] Eclipse Phase core deae4c13d989d6674a43b63d275c733b43a8df9c

## Armour
- [x] Eclipse Phase core Armor f568ca5960ca33bd749ed01614ae903cd357492b
- [x] Eclipse Phase core Exoskeletons f568ca5960ca33bd749ed01614ae903cd357492b

## Gear
- [x] Communications gear from Eclipse Phase core 0fb2e75a9b58b59734701257b4142b64984d032b
- [x] Covert and Espionage Tech from Eclipse Phase core 0fb2e75a9b58b59734701257b4142b64984d032b
- [x] Everyday Technology from Eclipse Phase core 0fb2e75a9b58b59734701257b4142b64984d032b
- [x] Nanotechnology from Eclipse Phase core 0fb2e75a9b58b59734701257b4142b64984d032b
- [x] Scavenger Tech from Eclipse Phase core 5eac2e8545e502af8e0c2a9f1c7c9f89066faf86
- [x] Survival Gear from Eclipse Phase core 9e2c4f41015d1b9995dad9249cda122cb2460fe7
- [x] Gear from Firewall 9e2c4f41015d1b9995dad9249cda122cb2460fe7
- [x] Gear from Gatecrashing 9e2c4f41015d1b9995dad9249cda122cb2460fe7
- [x] Gear from Panopticon 9e2c4f41015d1b9995dad9249cda122cb2460fe7
- [x] Gear from Rimward 75abe0f13926ab33b96bdc09c867f1a016d563c4
- [x] Gear from Sunward 75abe0f13926ab33b96bdc09c867f1a016d563c4

## Software
- [x] Programs from Eclipse Phase core c08ad418734699004bec713ddabb215575ccdd91
- [x] Software plugins from Transhuman 00c8e75cdc9fbc0f7f464cb68680b95ae4852821
- [x] Software from Firewall 743bbe7d781c54b5b841d78086c1f8755a50867e
- [x] Software from Panopticon 743bbe7d781c54b5b841d78086c1f8755a50867e

## Substances
- [x] Drugs, Nanodrugs, Narcoalgorithms, Petals, Psidrugs from Eclipse Phase core 3c8b62c1e8c98700ce0081bd251b6164473d3070
- [x] Chemicals from Eclipse Phase core 3c8b62c1e8c98700ce0081bd251b6164473d3070
- [x] Toxins, Nanotoxins, Pathogens from Eclipse Phase core 3c8b62c1e8c98700ce0081bd251b6164473d3070
- [x] Substances from Firewall 5e8b1115fac9c5b544200fae9fffa5f3e7acc436
- [x] Substances from Panopticon 30e079d271acb8a33fe3336124ac744f9aaf67a8

## Augmentations
- [x] Standard Augmentations f4ab65c97b32e8743627787e2063bf520ed3b895
- [x] Bioware from Eclipse Phase core 35a5c7ef0b3fb8944ccc7693d4aeeb303a590856
- [x] Cyberware  from Eclipse Phase core 35a5c7ef0b3fb8944ccc7693d4aeeb303a590856
- [x] Nanoware  from Eclipse Phase core 35a5c7ef0b3fb8944ccc7693d4aeeb303a590856
- [x] Cosmetic Mods  from Eclipse Phase core acf46a07efc491bd7fb9bcab3c2c901c81b50e39
- [x] Robotic Enhancements  from Eclipse Phase core acf46a07efc491bd7fb9bcab3c2c901c81b50e39
- [x] Software Upgrades from Transhuman acf46a07efc491bd7fb9bcab3c2c901c81b50e39
- [x] Augmentations from Firewall acf46a07efc491bd7fb9bcab3c2c901c81b50e39
- [x] Augmentations from Gatecrashing acf46a07efc491bd7fb9bcab3c2c901c81b50e39
- [x] Augmentations from Panopticon acf46a07efc491bd7fb9bcab3c2c901c81b50e39
- [x] Augmentations from Rimward acf46a07efc491bd7fb9bcab3c2c901c81b50e39
- [x] Augmentations from Sunward acf46a07efc491bd7fb9bcab3c2c901c81b50e39

## Other
- [x] Armour Mods  from Eclipse Phase core 743bbe7d781c54b5b841d78086c1f8755a50867e
- [x] Armour Mods  from Rimward 743bbe7d781c54b5b841d78086c1f8755a50867e
- [x] Weapon Accessories  from Eclipse Phase core 743bbe7d781c54b5b841d78086c1f8755a50867e

Others to come

**Comment by o-alex** [comment]
will start working on Clubs this evening

**Comment by liroth** [comment]
Morphs G-L done, M-N next.

**Comment by Bathtor** [comment]
Note that I changed the procedure slightly to accomodate macro generation. It's actually easier now.

**Comment by o-alex** [comment]
done:  
weapons: clubs
morphs O-R, S, T-X
Negative traits from Eclipse Phase core

doing:
traits: Positive/Negative Traits Transhuman

**Comment by Bathtor** [comment]
If you have any started files, note that you now need a new import: 
```scala
import com.lkroll.common.macros.Macros
```

**Comment by Bathtor** [comment]
Loooots of new things to do for bored people ;)

**Comment by o-alex** [comment]
Doing:
Drugs, Nanodrugs, Narcoalgorithms, Petals, Psidrugs from Eclipse Phase core

**Comment by joesinghaus** [comment]
Working on bioware + cyberware + nanoware.
