### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by WallaceMcGregor** [Bathtor/EPCompendium#24]
Hi.

Could be possible to translate the compendium in a similar way the sheets, or it have to be created with a full new compendium?

**Comment by Bathtor** [comment]
I don't know, how are the sheets translated? The compendium essentially generates JSON (embedded in a tiny bit of JS), so if you have an (semi-)automated way of translating JSON like Roll20 does, I'm sure you could do that.
I purposefully kept the data and the code well separated, so people could go an roll their own compendium entries.

**Comment by Bathtor** [comment]
I'm going to close this, since I don't think I have anything to do here. Reopen it, if there's something concrete I need to do to support this better.
